export default [
  {
    id: 'hashquark',
    name: 'HashQuark',
    open: true,
    operator_address: 'cosmosvaloper1cgh5ksjwy2sd407lyre4l3uj2fdrqhpkzp06e6',
    time: '2019.05.31 11:00 - 2019.06.13 18:00',
    imgs: {
      zh: {
        big: require('../assets/campaign/hashquark-zh-big.png'),
        small: require('../assets/campaign/hashquark-zh-small.png')
      },
      en: {
        big: require('../assets/campaign/hashquark-zh-big.png'),
        small: require('../assets/campaign/hashquark-zh-small.png')
      },
    },
    banner: {
      zh: require('../assets/campaign/hashquark-zh-big.png'),
      en: require('../assets/campaign/hashquark-zh-big.png'),
    },
    activity: {
      name: {
        zh: '请你瓜分 2000 个 ATOM',
        en: '请你瓜分 2000 个 ATOM',
      },
      time: '2019.05.31 11:00 - 2019.06.13 18:00',
      url: '/cosmos/campaign/hashquark',
    },
    locales: {
      zh: {
        delegated: '已委托（活动期间）',
        total_delegated: '委托总量',
        total_delegator: '委托者',
        top_delegations: '委托排名',
        campaign_details: '活动详情',
        campaign_time: '活动时间',
        campaign_rule: '活动规则',
        campaign_reward: '奖励派发',
        campaign_state: '活动说明',
        rule1: '一重礼',
        rule2: '二重礼',
        rule1_title: '委托赢空投',
        rule2_title: '排位赢 imKey',
        rule1_desc1: '活动期间，向 Hashquark 节点委托 ATOM，即可参与瓜分 1000 ATOM！',
        rule1_desc2: '单人奖励 =（已委托代币 / 总委托代币）X 1000 ATOM X 首周奖励 1.2 倍',
        rule1_remark1: '注：首周奖励为 1.2 倍，先到先得！委托越多，奖励越多！',
        rule2_desc1: '活动期间，向 Hashquark 节点累计质押 ATOM 数量排名前三的用户可额外获得 TOP 3 惊喜大奖：',
        rule2_top1: '400 ATOM + 价值 999 元限量 imKey',
        rule2_top2: '300 ATOM + 价值 999 元限量 imKey',
        rule2_top3: '100 ATOM + 价值 999 元限量 imKey',
        reward_desc1: '本次活动奖励将在活动结束后统一进行发放，请耐心等待；',
        reward_desc2: '截止至活动结束，向 Hashquark 质押 ATOM 数量 TOP 3 的用户将于活动结束后收到含有 imKey 兑换码及兑换方式的消息通知；',
        state_desc1: '1. 活动期间任意时间可质押，次数不限，活动结束（6.13 18:00）前赎回或改票视为无效；',
        state_desc2: '2. 一重礼「 单个用户可获奖励」公式中时间限制均为活动期间，总委托代币为活动期间通过 imToken 质押给 Hashquark ≥10 ATOM 数量的总和；',
        delegate_now: '立即委托',
        end_time: '距活动结束',
        campaign_over: '活动截止至 2019-06-11 18:00 已结束，感谢参与！',
        campaign_over_button: '活动结束',
        day: '天',
        success_delegate: '已成功委托',
        success_delegate_desc: '空投将在活动结束后统一发放，感谢支持~',
        confirm: '确认',
      },
      en: {
        delegated: '已委托（活动期间）',
        total_delegated: '委托总量',
        total_delegator: '委托者',
        top_delegations: '委托排名',
        campaign_details: '活动详情',
        campaign_time: '活动时间',
        campaign_rule: '活动规则',
        campaign_reward: '奖励派发',
        campaign_state: '活动说明',
        rule1: '一重礼',
        rule2: '二重礼',
        rule1_title: '委托赢空投',
        rule2_title: '排位赢 imKey',
        rule1_desc1: '活动期间，向 Hashquark 节点委托 ATOM，即可参与瓜分 1000 ATOM！',
        rule1_desc2: '单人奖励 =（已委托代币 / 总委托代币）X 1000 ATOM X 首周奖励 1.2 倍',
        rule1_remark1: '（注：首周奖励为 1.2 倍，先到先得！委托越多，奖励越多！）',
        rule2_desc1: '活动期间，向 Hashquark 节点累计质押 ATOM 数量排名前三的用户可额外获得 TOP 3 惊喜大奖：',
        rule2_top1: '400 ATOM + 价值 999 元限量 imKey',
        rule2_top2: '300 ATOM + 价值 999 元限量 imKey',
        rule2_top3: '100 ATOM + 价值 999 元限量 imKey',
        reward_desc1: '本次活动奖励将在活动结束后统一进行发放，请耐心等待；',
        reward_desc2: '截止至活动结束，向 Hashquark 质押 ATOM 数量 TOP 3 的用户将于活动结束后收到含有 imKey 兑换码及兑换方式的消息通知；',
        state_desc1: '1. 活动期间任意时间可质押，次数不限，活动结束（6.13 18:00）前赎回或改票视为无效；',
        state_desc2: '2. 一重礼「 单个用户可获奖励」公式中时间限制均为活动期间，总委托代币为活动期间通过 imToken 质押给 Hashquark ≥10 ATOM 数量的总和；',
        delegate_now: '立即委托',
        end_time: '距活动结束',
        campaign_over: '活动截止至 2019-06-11 18:00 已结束，感谢参与！',
        campaign_over_button: '活动结束',
        day: '天',
        success_delegate: '已成功委托',
        success_delegate_desc: '空投将在活动结束后统一发放，感谢支持~',
        confirm: '确认',
      },
    },
  }
]